//
//  ClientSystemDetailsData.swift
//  AgroChem
//
//  Created by Aizat Ozbekova on 5/5/24.
//

import UIKit

final class ClientSystemDetailsData {

    static let bobData: [SystemCategories] = [
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ger",
                                                  name: "Гербициды",
                                                  color: .systemRed),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Тристар, КС",
                                   subName: "Прометрин, 500 г/л",
                                   faza: "faza",
                                   subFaza: "посев",
                                   norma: "norma",
                                   subNorma: "2.5 - 3.5 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Сапфир, ВРК",
                                   subName: "Имазетапир, 100 г/л",
                                   faza: "faza",
                                   subFaza: "с посев по 2-й тройной лист",
                                   norma: "norma",
                                   subNorma: "0.5 - 0.75 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Илот, ВР",
                                   subName: "Имазамокс, 40 г/л",
                                   faza: "faza",
                                   subFaza: "1-й тройной лист",
                                   norma: "norma",
                                   subNorma: "0.75 - 1 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Гербикс, ВК",
                                   subName: "МЦПА, 500 г/л",
                                   faza: "faza",
                                   subFaza: "с 1-й тройной лист по 2-й тройной лист",
                                   norma: "norma",
                                   subNorma: "0.5 - 0.8 л/га",
                                   color: .systemRed)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ins",
                                                  name: "Инсектициды",
                                                  color: .systemBlue),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Аккорд, КЭ",
                                   subName: "Альфа-циперметрин, 100 г/л",
                                   faza: "faza",
                                   subFaza: "c начало бутонизации по формирование бобов",
                                   norma: "norma",
                                   subNorma: "0.1 л/га",
                                   color: .systemBlue)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1min",
                                                  name: "Минеральные удобрения",
                                                  color: .systemGreen),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "АгроМинерал",
                                   subName: "Стручковые и Бобовые",
                                   faza: "faza",
                                   subFaza: "2-й тройной лист",
                                   norma: "norma",
                                   subNorma: "2 л/га",
                                   color: .systemGreen)
        ])
    ]

    static let zerData: [SystemCategories] = [
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1pro",
                                                  name: "Протравители семян",
                                                  color: .systemPurple),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Грандсил Ультра, КС",
                                   subName: "Флутриафол, 75 г/л + Тебуконазол, 45 г/л + Имазалил, 20 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "0.4 - 0.5 л/т",
                                   color: .systemPurple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Пионер, КС",
                                   subName: "Флутриафол, 25 г/л + Тиабендазол, 25 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "1.5 - 2 л/т",
                                   color: .systemPurple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Стрит, КС",
                                   subName: "Имидаклоприд, 600 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "0.3 - 0.75 л/т",
                                   color: .systemPurple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Виталон, КС",
                                   subName: "Тирам, 400 г/л + Тебуконазол, 14 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "1.5 - 2 л/т",
                                   color: .systemPurple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Грифон, КС",
                                   subName: "Ацетамиприд, 100 г/л + Флудиоксонил, 25 г/л + Дифеноконазол, 25 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "1.5 - 2 л/т",
                                   color: .systemPurple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Грандсил, КС",
                                   subName: "Тебуконазол, 60 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян",
                                   norma: "norma",
                                   subNorma: "0.4 - 0.5 л/т",
                                   color: .systemPurple)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ger",
                                                  name: "Гербициды",
                                                  color: .systemRed),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Глифор, ВР",
                                   subName: "Глифосат (изопропиламинная соль), 360 г/л",
                                   faza: "faza",
                                   subFaza: "до посева",
                                   norma: "norma",
                                   subNorma: "2 - 8 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Гран-при, ВДГ",
                                   subName: "Трибенурон-метил, 750 г/кг",
                                   faza: "faza",
                                   subFaza: "с начало кущения, по выход в трубку",
                                   norma: "norma",
                                   subNorma: "0.015 - 0.025 кг/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Тайгер, ЭМВ",
                                   subName: "Феноксапроп-П-этил, 69 г/л + Клоквинтосет-мексил, 34.5 г/л",
                                   faza: "faza",
                                   subFaza: "с 1-2-3 лист, по полная спелость",
                                   norma: "norma",
                                   subNorma: "0.8 - 1 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Гарнизон, ВP",
                                   subName: "Бентазон, 480 г/л",
                                   faza: "faza",
                                   subFaza: "начало кущения",
                                   norma: "norma",
                                   subNorma: "2 - 4 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Арбалет, СЭ",
                                   subName: "2,4-Д (2-этилгексиловый эфир), 300 г/ л + Флорасулам, 6.25 г/л",
                                   faza: "faza",
                                   subFaza: "начало кущения",
                                   norma: "norma",
                                   subNorma: "0.4 - 0.6 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Рефери, ВГР",
                                   subName: "Дикамба, 351 г/л",
                                   faza: "faza",
                                   subFaza: "с начало кущения, по выход в трубку",
                                   norma: "norma",
                                   subNorma: "0.17 - 0.2 л/га",
                                   color: .systemRed)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1fun",
                                                  name: "Фунгициды",
                                                  color: .purple),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Бульдог, КЭ",
                                   subName: "Пропиконазол, 250 г/л",
                                   faza: "faza",
                                   subFaza: "с начало кущения \nпо налив, молочная спелость",
                                   norma: "norma",
                                   subNorma: "0.5 л/га",
                                   color: .purple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Ципрос, КЭ",
                                   subName: "Пропиконазол, 250 г/л + Ципроконазол, 80 г/л",
                                   faza: "faza",
                                   subFaza: "с начало кущения \nпо налив, молочная спелость",
                                   norma: "norma",
                                   subNorma: "0.4 - 0.5 л/га",
                                   color: .purple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Армадекс, КС",
                                   subName: "Карбендазим, 500 г/л",
                                   faza: "faza",
                                   subFaza: "с начало кущения \nпо налив, молочная спелость",
                                   norma: "norma",
                                   subNorma: "0.3 - 0.6 л/га",
                                   color: .purple),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Эпоксин, КС",
                                   subName: "Азоксистробин, 200 г/л + Эпоксиконазол, 100 г/л",
                                   faza: "faza",
                                   subFaza: "с флаговый лист \nпо колошение",
                                   norma: "norma",
                                   subNorma: "0.7 - 1 л/га",
                                   color: .purple)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ins",
                                                  name: "Инсектициды",
                                                  color: .systemBlue),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Норил, КЭ",
                                   subName: "Хлорпирифос, 500 г/л + Циперметрин, 50 г/л",
                                   faza: "faza",
                                   subFaza: "обработка семян ",
                                   norma: "norma",
                                   subNorma: "0.75 - 1 л/га",
                                   color: .systemBlue),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Восторг, КС",
                                   subName: "Клотианидин, 140 г/л + Лямбда- цигалотрин, 100 г/л",
                                   faza: "faza",
                                   subFaza: "с 1-2-3 лист, \nпо полная спелость",
                                   norma: "norma",
                                   subNorma: "0.1 - 0.25 л/га",
                                   color: .systemBlue),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Аккорд, КЭ",
                                   subName: "Альфа-циперметрин, 100 г/л",
                                   faza: "faza",
                                   subFaza: "с 1-2-3 лист, \nпо полная спелость",
                                   norma: "norma",
                                   subNorma: "0.1 - 0.15 л/га",
                                   color: .systemBlue),
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1min",
                                                  name: "Минеральные удобрения",
                                                  color: .systemGreen),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "АгроМинерал",
                                   subName: "Зерновые",
                                   faza: "faza",
                                   subFaza: "1-2-3 лист",
                                   norma: "norma",
                                   subNorma: "1 - 1.5 л/га",
                                   color: .systemGreen),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "АгроМинерал",
                                   subName: "Зерновые",
                                   faza: "faza",
                                   subFaza: "с конец кущения, \nпо выход в трубку",
                                   norma: "norma",
                                   subNorma: "1 - 1.5 л/га",
                                   color: .systemGreen)
        ])
    ]
    static let karData: [SystemCategories] = [
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1pro",
                                                  name: "Протравители семян",
                                                  color: .systemPurple),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Грифон, КС",
                                   subName: "Ацетамиприд, 100 г/л + Флудиоксонил, 25 г/л + Дифеноконазол, 25 г/л",
                                   faza: "faza",
                                   subFaza: "до посева",
                                   norma: "norma",
                                   subNorma: "0.4 л/т",
                                   color: .systemPurple)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ger",
                                                  name: "Гербициды",
                                                  color: .systemRed),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Глифор, ВР",
                                   subName: "Глифосат (изопропиламинная соль), 360 г/л",
                                   faza: "faza",
                                   subFaza: "до посева",
                                   norma: "norma",
                                   subNorma: "2 - 8 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Гильотина, ВДГ",
                                   subName: "Метрибузин, 700 г/кг",
                                   faza: "faza",
                                   subFaza: "до посева",
                                   norma: "norma",
                                   subNorma: "0.5 - 1.4 кг/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Гербикс, ВК",
                                   subName: "МЦПА, 500 г/л",
                                   faza: "faza",
                                   subFaza: "до всходов",
                                   norma: "norma",
                                   subNorma: "1.2 л/га",
                                   color: .systemRed),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Тристар, КС",
                                   subName: "Прометрин, 500 г/л",
                                   faza: "faza",
                                   subFaza: "до всходов",
                                   norma: "norma",
                                   subNorma: "2 - 3.5 л/га",
                                   color: .systemRed)
        ]),
        SystemCategories(
        systemCategory: ClientSystemCategoryModel(image: "1ins",
                                                  name: "Инсектициды",
                                                  color: .systemBlue),
        categoryDetails: [
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Аккорд, КЭ",
                                   subName: "Альфа-циперметрин, 100 г/л",
                                   faza: "faza",
                                   subFaza: "c прорастание \nпо цветение и образование клубней",
                                   norma: "norma",
                                   subNorma: "0.07 - 0.1 л/га",
                                   color: .systemBlue),
        ClientCategoryDetailsModel(image: "k4",
                                   name: "Калаш, ВРК",
                                   subName: "Имидаклоприд, 200 г/л",
                                   faza: "faza",
                                   subFaza: "с прорастание \nпо цветение и образование клубней",
                                   norma: "norma",
                                   subNorma: "0.1 л/га",
                                   color: .systemBlue)
        ])
    ]
}
